### ISSUE TITLE
positioning edge case introduced by content edit in section 6, at 'Of course: ...'

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#34]
In this commit:
`1f9895`

Sorry, Sally: I'm working through and improving the rewrite, and it threw this up.

**Comment by shadoof** [comment]
I could fix this with a content edit, but I though you'd want to know about it anyway.

**Comment by cqx931** [comment]
Let me take a look

**Comment by cqx931** [comment]
That covers a case I forgot to mention for the remaining positioning issues. For this case, no matter which anchor we choose, we couldn't have enough space before the anchor and there is also no margin spaces to borrow because the anchor all starts within the first line.  In this case and, should b content just fill in the space of a from the beginning and neglecting the fixed position of anchors?

**Comment by shadoof** [comment]
My answer is: yes.

The only other possibility would be to move on to a strategy for text pairs for which the 'B units' are much larger. See my comments on #15 .

**Comment by cqx931** [comment]
this should be fixed now.
