### ISSUE TITLE
Potential jsdiff issue: space being the shared component?

### ISSUE THREAD

**Issue by cqx931** [shadoof/rtwtr#62]
I was trying to compare the result from jsdiff and the one we got from command line, and found this particular case:

![Screenshot 2021-03-17 at 6 17 07 PM](https://user-images.githubusercontent.com/3056154/111509470-0de0cd00-874d-11eb-8430-9abc17def2af.png)

Whereas our old method parsing it as following:
<img width="238" alt="Screenshot 2021-03-17 at 6 24 52 PM" src="https://user-images.githubusercontent.com/3056154/111510451-1554a600-874e-11eb-8c1a-55aefb510672.png">

Both `diffWordsWithSpace()` and `diffWords()` seem to be treating this case the same way.

@shadoof  you mentioned this in the other ticket, I'm quoting this here because I find it related:

> Yes, ultimately we much treat spaces as first class entities, real things, not white space. I'm inclined, for example, to be consistent in using Diff.wordDiffWithSpace() rather than wordDiff() (if I've remember those method names right)._

**Comment by shadoof** [comment]
Nice catch. Gotta think about this! Argh.

 

On March 17, 2021 at 1:30:24 PM, cqx931 ***@***.***) wrote:

I was trying to compare the result from jsdiff and the one we got from command line, and found this particular case:



Whereas our old method parsing it as following:


Both diffWordsWithSpace() and diffWords() seem to be treating this case the same way.

@shadoof you mentioned this in the other ticket, I'm quoting this here because I find it related:
Yes, ultimately we much treat spaces as first class entities, real things, not white space. I'm inclined, for example, to be consistent in using Diff.wordDiffWithSpace() rather than wordDiff() (if I've remember those method names right).

**Comment by shadoof** [comment]
hi Sally, I thought about and did some hacking on this which did not go so well. Then I realized that currently this would not affect the *behavior* of rtwtr because hovering over a 'shared' space or spaces would not trigger an animation. If I'm wrong about this then re-open but this way of parsing in itself would do no more harm than causing your overlayed spans algorithm to define a few extra shared spans without any effect on visualization or animation.

I'll commit my latest version of the branch. There will only be slight tweaks to my tagFriendlyWordDiff(), a post processor for the standard diffWordsWithSpace() output that does make it conform to what your parseDiff is expecting to receive.
