### ISSUE TITLE
visjsdiff users interface: some CSS gets lost when loading new a&b files and reformatting - quick one?

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#64]
hi Sally: I've been doing my best to tweak your ui for rtwtr to suit what I'd like for VIA. I've tried to make it so only one page (with ID "#page1" is created) and then I've reconfigured the menu so that it only has the prev and next buttons which then remove() the current page1 and call functions for loading a&b texts, parsing, and recreating the page.

But I can't quite get this right and my current hack must also delete some of your CSS (class?) styling attributes.

Can you help?

And I'll pay attention to your fix so that I get better at this DOM manipulation. (I'd like to get better at this ;)

**Comment by cqx931** [comment]
Please check: https://github.com/cqx931/rtwtr/commit/987873834bf0aeb559422bd6b04f6e500c1c0f07

The issue was that parseDiff() function used to try to create a new "#content" element every time it is called and in [initializeCSS()](https://github.com/cqx931/rtwtr/blob/viajsdiff/js/animation.js#L469) it adds the styles to `#content` element.

So I modified parseDiff() so that it only add a new "#content" element if it can't find one and that should fix the issue here.

**Comment by shadoof** [comment]
Thanks Sally. Got it. Works for me and closing.
